services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: spotify
      MYSQL_PASSWORD: spotify
      MYSQL_DATABASE: spotify
      MYSQL_ROOT_PASSWORD: spotify
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
    - 3307:3306
    expose:
      - 3307